### PR TITLE
Introduce the ability to add multiple wireless network configurations

### PR DESCRIPTION
**Pull request by tmecklem**
Related to https://github.com/nerves-project/nerves_network/issues/72.

Add `add_network/2`, `remove_all_networks/1`, and `reassociate/1`
functions to give more fine grained control over the configuration and
activation process while shielding callers from implementation details,
and reworks `set_network/2` to use the new methods.

Add documentation for `:priority` which is useful when configuring
Multiple networks.

### CODE REVIEW

**Review by fhunleth — APPROVED** [review]
I didn't test this out, but I like what you did. This is a nice improvement!

**Comment by newellista** [comment]
What are the chances of getting this merged into master soon?

**Comment by fhunleth** [comment]
@ConnorRigby

**Review by ConnorRigby — APPROVED** [review]

**Comment by ConnorRigby** [comment]
Sorry for taking so long to get this merged. Looks great to me.

**Pull request merged**
