### PR TITLE
add a timeout for scanning.

### PR DESCRIPTION
**Pull request by ConnorRigby**
maybe 5 seconds isnt long enough?

### CODE REVIEW

**Comment by fhunleth** [comment]
I missed this. This seems like a reasonable change. Are you using this on Farmbot, and if so, has 5 seconds turned out to be a good value?

**Comment by ConnorRigby** [comment]
I don't use it anymore, but at one time I did. 5 seconds was enough at the time tho

**Review by GregMefford — APPROVED** [review]
Seems like a good idea to time out after a while instead of waiting forever.

**Review by mobileoverlord — APPROVED** [review]

**Comment by ConnorRigby** [comment]
Whoa i forgot about this. Its been approved so merging.

**Pull request merged**
